vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        userPicture:
            uri_prefix: /uploads/images/users/picture
            upload_destination: '%kernel.project_dir%/public/uploads/images/users/picture'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'firstName' }
        
