vich_uploader:
    db_driver: orm

    mappings:
        productPicture:
            uri_prefix: /uploads/images/product/picture
            upload_destination: '%kernel.project_dir%/public/uploads/images/product/picture'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'name' }
        userPicture:
            uri_prefix: /uploads/images/users/picture
            upload_destination: '%kernel.project_dir%/public/uploads/images/users/picture'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'firstName' }
        
