name: app

type: php:8.1

dependencies:
    php:
        composer/composer: "^2"
runtime:
    extensions:
        - apcu
        - mbstring
        - sodium
        - iconv
        - ctype
        - pdo_pgsql

relationships:
    database: "database:postgresql"

build:
    flavor: none
disk: 512
web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"
mounts:
    "/var": { source: local, source_path: var }
    
hooks:
    build: |
        set -x -e
        curl -fs https://get.symfony.com/cloud/configurator | bash
        
        NODE_VERSION=18 symfony-build
    deploy: |
        set -x -e
        symfony-deploy
