# The name of this app. Must be unique within a project.
name: clickbill

# The runtime the application uses. The 'type' key defines the base container
# image that will be used to run the application. There is a separate base
# container image for each primary language for the application,
# in multiple versions. Check the PHP documentation
# (https://docs.platform.sh/languages/php.html#supported-versions)
# to find the supported versions for the 'php' type.
type: 'php:8.1'

# The following block defines writable directories for storing cache and logs.
mounts:
  '/clickbill/cache': 'shared:files/cache'
  '/clickbill/logs': 'shared:files/logs'

# The size of the persistent disk of the application (in MB).
disk: 2048

# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form '<service name>:<endpoint name>'.
relationships:
    postgresdatabase: 'dbpostgres:postgresql'

# Use Composer 2 to handle dependencies.
dependencies:
    php:
        composer/composer: '^2'

# The type of the application to build.
build:
  flavor: composer

hooks:
    build: |
      set -e
      composer install --no-dev --optimize-autoloader
      npm run build
      php bin/console --env=prod cache:clear
    deploy: |
      set -e
      php bin/console --env=prod cache:warmup

# File location to handle requests
web:
  locations:
    '/':
      root: "public"
      passthru: "/index.php"
