controllers_security:
    resource: ../src/Controller/SecurityController.php
    type: attribute

controllers_front:
    resource: ../src/Controller/Front
    type: attribute
    name_prefix:  front_
    prefix: /app

controllers_back:
    resource: ../src/Controller/Back
    type: attribute
    name_prefix:  back_
    prefix: /admin

controllers_public:
    resource: ../src/Controller/Public
    type: attribute
    name_prefix:  public_
