controllers_security:
    resource: ../src/Controller/SecurityController.php
    type: attribute

controllers_front_company:
    resource: ../src/Controller/Front/Company
    type: attribute
    name_prefix:  front_company_
    prefix: /company

controllers_front_accountant:
    resource: ../src/Controller/Front/Accountant
    type: attribute
    name_prefix:  front_accountant_
    prefix: /accountant

controllers_back:
    resource: ../src/Controller/Back
    type: attribute
    name_prefix:  back_
    prefix: /admin

controllers_public:
    resource: ../src/Controller/Public
    type: attribute
    name_prefix:  public_
